# Generated by Django 4.2.5 on 2023-10-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_person_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
